#############################
# GitLab Runner Target Role #
#############################
---
Description: GitLab Runner Target Role

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Role Configuration"
        Parameters:
          - AssumeRoleArn
    ParameterLabels:
      AssumeRoleArn:
        default: "Role that can assume role created by this template"

Parameters:
  AssumeRoleArn:
    Type: String
    Default: arn:aws:iam::123456789012:root
    Description: Required

Resources:
  IamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            AWS: !Ref AssumeRoleArn
          Action: sts:AssumeRole
      Description: Permissions GitLab Runners assume

  IamPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - cloudformation:DetectStackSetDrift
              - cloudformation:ListExports
              - cloudformation:DescribeStackDriftDetectionStatus
              - cloudformation:DetectStackDrift
              - cloudformation:ListStackSetOperations
              - cloudformation:ListStackInstances
              - cloudformation:ListTypes
              - cloudformation:DescribeStackResource
              - cloudformation:CreateChangeSet
              - cloudformation:ListTypeRegistrations
              - cloudformation:ListStackSetOperationResults
              - cloudformation:DetectStackResourceDrift
              - cloudformation:EstimateTemplateCost
              - cloudformation:DescribeStackEvents
              - cloudformation:DescribeStackSetOperation
              - cloudformation:UpdateStack
              - cloudformation:DescribeAccountLimits
              - cloudformation:DescribeChangeSet
              - cloudformation:ExecuteChangeSet
              - cloudformation:ListStackResources
              - cloudformation:ListStacks
              - cloudformation:DescribeType
              - cloudformation:ListImports
              - cloudformation:DescribeStackInstance
              - cloudformation:DescribeStackResources
              - cloudformation:DescribeTypeRegistration
              - cloudformation:GetTemplateSummary
              - cloudformation:DescribeStacks
              - cloudformation:DescribeStackResourceDrifts
              - cloudformation:GetStackPolicy
              - cloudformation:DescribeStackSet
              - cloudformation:ListStackSets
              - cloudformation:GetTemplate
              - cloudformation:TagResource
              - cloudformation:UntagResource
              - cloudformation:ValidateTemplate
              - cloudformation:ListChangeSets
              - cloudformation:ListTypeVersions
            Resource: "*"
      PolicyName: GitLabRunnerPolicy
      Roles:
        - !Ref IamRole

Outputs:
  IamRoleArn:
    Description: IAM Role for GitLab Runner to assume
    Value: !GetAtt IamRole.Arn
