---
Description: GitLab Control Stack

Parameters:
  CertificateID:
    Type: String
    Description: SSL Certificate ARN (Required)

  HostZone:
    Type: String
    Description: DNS Zone to create A records (Required)

  BastionKeyName:
    Type: String
    Description: Enter keyname for Bastion instance access. (Required)

  EFSPerformance:
    Type: String
    Default: generalPurpose
    AllowedValues:
      - generalPurpose
      - maxIO
    Description: EFS Performance Type

  IPWhiteList:
    Type: String
    Default: 0.0.0.0/0
    Description: IP range allowed to VPN into Bastion. (Not recommended to leave default)

  GitLabKeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Enter keyname for GitLab instance access.

  ApplicationImage:
    Type: AWS::EC2::Image::Id
    Default: ami-643b1972
    Description: Image to use for GitLab servers

  ApplicationSize:
    Type: String
    Default: t2.large
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.large
      - m3.medium
      - m4.large
      - m4.xlarge
      - c4.large
    Description: GitLab Application instance size.

  CacheSize:
    Type: String
    Default: cache.m3.medium
    AllowedValues:
      - cache.t2.micro
      - cache.t2.small
      - cache.m3.medium
      - cache.m4.large
      - cache.r3.large
    Description: Cache Node instance size.

  DatabaseSize:
    Type: String
    Default: db.m4.large
    AllowedValues:
      - db.t2.micro
      - db.t2.small
      - db.m4.large
      - db.m4.xlarge
      - db.m4.2xlarge
    Description: Database Instance Size

  DatabaseStorage:
    Type: String
    Default: 100
    Description: Size of database in GB. Must be at least 100. Cannot exceed 6000.

  DatabaseIOPS:
    Type: String
    Description: |
      Database IOPS. Leave blank to use gp2 storage. Otherwise see: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Storage.html#USER_PIOPS

  DatabasePassword:
    Type: String
    NoEcho: true
    MinLength: 8
    MaxLength: 41
    Description: Enter a database password. Do not include characters " \ or @.

Resources:
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        BastionKeyName:
          Ref: BastionKeyName
        IPWhiteList:
          Ref: IPWhiteList
      TemplateURL: <URL of GitLab Bucket>/VPC.yml

  SNSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: <URL of GitLab Bucket>/SNS.yml

  ApplicationStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
    - NetworkStack
    - SNSStack
    Properties:
      Parameters:
        GitLabKeyName:
          Ref: GitLabKeyName
        ApplicationSize:
          Ref: ApplicationSize
        ApplicationImage:
          Ref: ApplicationImage
        CertificateID:
          Ref: CertificateID
        HostZone:
          Ref: HostZone
      TemplateURL: <URL of GitLab Bucket>/Application.yml

  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
    - NetworkStack
    - ApplicationStack
    - SNSStack
    Properties:
      Parameters:
        DatabaseStorage:
          Ref: DatabaseStorage
        DatabaseIOPS:
          Ref: DatabaseIOPS
        DatabaseSize:
          Ref: DatabaseSize
        DatabasePassword:
          Ref: DatabasePassword
      TemplateURL: <URL of GitLab Bucket>/RDS.yml

  CacheStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
    - NetworkStack
    - ApplicationStack
    - SNSStack
    Properties:
      Parameters:
        CacheSize:
          Ref: CacheSize
      TemplateURL: <URL of GitLab Bucket>/ElastiCache.yml

  EFSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
    - NetworkStack
    - ApplicationStack
    Properties:
      Parameters:
        EFSPerformance:
          Ref: EFSPerformance
      TemplateURL: <URL of GitLab Bucket>/EFS.yml

Outputs:
  BastionIP:
    Description: Public IP of the SSH Bastion
    Value:
      Fn::GetAtt: NetworkStack.Outputs.BastionIP

  DatabaseEndpoint:
    Description: Endpoint of PostgreSQL Server
    Value:
      Fn::GetAtt: DatabaseStack.Outputs.DatabaseEndpoint

  CacheEndpoint:
    Description: Endpoint of Redis Server
    Value:
      Fn::GetAtt: CacheStack.Outputs.CacheEndpoint

  EFSEndpoint:
    Description: Endpoint of EFS
    Value:
      Fn::GetAtt: EFSStack.Outputs.EFSEndpoint

  TestURL:
    Description: Application Test URL
    Value:
      Fn::GetAtt: ApplicationStack.Outputs.TestURL

  URL:
    Description: Application URL
    Value:
      Fn::GetAtt: ApplicationStack.Outputs.URL

  SNSTopic:
    Description: SNS Topic
    Value:
      Fn::GetAtt: SNSStack.Outputs.SNSTopic
      